# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
  displayName: 'Maven build'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'java -cp "target/test-classes:target/classes:target/dependency/*" io.cucumber.core.cli.Main --glue com.example.cucumber.steps src/test/resources/Hooks/Hooks.feature'
  displayName: 'Run Cucumber tests'
